/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2019-07-28 11:57:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ContactUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("<title>www.CarrierMithr.com</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("<!--\n");
      out.write(".body {\n");
      out.write("        margin:0%;\n");
      out.write("}\n");
      out.write("a:link {\n");
      out.write("\tcolor: #000066;\n");
      out.write("\ttext-decoration: underline;\n");
      out.write("}\n");
      out.write("a:visited {\n");
      out.write("\ttext-decoration: underline;\n");
      out.write("\tcolor: #C0DCC0;\n");
      out.write("}\n");
      out.write("a:hover {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcolor: #996666;\n");
      out.write("}\n");
      out.write("a:active {\n");
      out.write("\ttext-decoration: underline;\n");
      out.write("\tcolor: #FF9999;\n");
      out.write("}\n");
      out.write(".style11 {\n");
      out.write("\tcolor: #660066\n");
      out.write("}\n");
      out.write(".style12 {color: #800040}\n");
      out.write(".style13 {\n");
      out.write("\tcolor: #333300\n");
      out.write("}\n");
      out.write("-->\n");
      out.write("</style>\n");
      out.write("<body style=\"margin:0px\" bgcolor=\"#4E2B21\">\n");
      out.write("<table width=\"100%\" height=\"707\" border=\"1\" valign=\"top\" >\n");
      out.write("  <tr>\n");
      out.write("    <td height=\"78\" colspan=\"2\" bgcolor=\"#624631\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("</td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td width=\"7\" height=\"621\" bgcolor=\"#624631\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.html", out, false);
      out.write("</td>\n");
      out.write("    <td width=\"747\" valign=\"top\" bgcolor=\"#CC9966\">\n");
      out.write("      <h1 align=\"center\" class=\"style63 style11\">Carreer Mithr </h1>\n");
      out.write("      <h3 align=\"center\" class=\"style64 style12\">5 Cat Road,Mishra Nagar INDORE</h3>\n");
      out.write("      <h3 align=\"center\" class=\"style64 style12\">Madhya Pradesh-09 </h3>\n");
      out.write("      <p align=\"center\" class=\"style12\">&nbsp;</p>\n");
      out.write("                         <hr align=\"center\" size=\"4\" color=\"purple\">\n");
      out.write("                         <p><br>\n");
      out.write("                            </hr>\n");
      out.write("                            <font name=\"Times New Roman\"color=\"#3by2\"> </p>\n");
      out.write("                         <p>\n");
      out.write("\n");
      out.write("          <h1 class=\"style63\">&nbsp;</h1>\n");
      out.write("          <h4 align=\"right\" class=\"style65 style13\"> <span class=\"style70\">Phone:</span> 0731-2481706</h4>\n");
      out.write("          <h4 align=\"right\" class=\"style65 style13\"><span class=\"style70\">Mob:</span> 07828726995</h4>\n");
      out.write("          <p align=\"left\" class=\"style65 style13\"><span class=\"style67\"><em>Email</em>:</span> carreermithr@yahoo.com  </p>\n");
      out.write("          <p class=\"style64\"><img src=\"ist2_4552254-recruitment[1].jpg\" width=\"380\" height=\"254\"></p>\n");
      out.write("          <p class=\"style64\">&nbsp; </p>\n");
      out.write("          <p class=\"style64\">&nbsp;</p>\n");
      out.write("          <p class=\"style64\">&nbsp;</p>\n");
      out.write("          <p class=\"style64\">&nbsp; </p>\n");
      out.write("\n");
      out.write("                         </p>    </td>\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
