/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2019-07-28 09:46:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\n");
      out.write("    <title>www.CarrierMithr.com</title>\n");
      out.write("    <style type=\"text/css\">\n");
      out.write("        <!--\n");
      out.write("        .body {\n");
      out.write("            margin:0%;\n");
      out.write("        }\n");
      out.write("        a:link {\n");
      out.write("            color: #003366;\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("        a:visited {\n");
      out.write("            text-decoration: underline;\n");
      out.write("            color: #660066;\n");
      out.write("        }\n");
      out.write("        a:hover {\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: #CC6633;\n");
      out.write("        }\n");
      out.write("        a:active {\n");
      out.write("            text-decoration: underline;\n");
      out.write("            color: #990033;\n");
      out.write("        }\n");
      out.write("        .style10 {\n");
      out.write("            color: #993300;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .style11 {\n");
      out.write("            color: #993333;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .style12 {color: #339933}\n");
      out.write("        body,td,th {\n");
      out.write("            color: #336633;\n");
      out.write("        }\n");
      out.write("        -->\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body style=\"margin:0px\">\n");
      out.write("<table width=\"100%\" height=\"492\" border=\"1\">\n");
      out.write("    <tr valign=\"top\">\n");
      out.write("        <td height=\"120\" colspan=\"2\" bgcolor=\"#624631\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("</td>\n");
      out.write("    </tr>\n");
      out.write("    <td width=\"1\" height=\"449\" valign=\"top\" bgcolor=\"#624631\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.html", out, false);
      out.write("</td>\n");
      out.write("    <td width=\"759\" valign=\"top\" bgcolor=\"#E8E1C7\">\n");
      out.write("        <div align=\"left\" >\n");
      out.write("            <p><img src=\"Login.jpg\" width=\"308\" height=\"263\"></p>\n");
      out.write("        </div>\n");
      out.write("        <form name=\"login\" method=\"post\" action=\"savelogindata.jsp\">\n");
      out.write("\n");
      out.write("            <div align=\"right\">\n");
      out.write("                <table width=\"219\" height=\"230\" border=\"1\" align=\"right\">\n");
      out.write("                    <tr valign=\"top\">\n");
      out.write("                        <td height=\"36\" bgcolor=\"#668CCC\"><p align=\"center\" class=\"style10\">Already a member???</p>            </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td width=\"209\" height=\"155\" bgcolor=\"#93C2E6\">\n");
      out.write("                            <div align=\"center\">\n");
      out.write("                                <p><strong>Enter Username </strong><br>\n");
      out.write("                                    <input name=\"username\" type=\"text\" id=\"username\" />\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                            <p align=\"center\"><strong>Enter Password\n");
      out.write("                                    <input name=\"password\" type=\"password\" id=\"password\" />\n");
      out.write("                            </strong></p>\n");
      out.write("\n");
      out.write("                            <label></label>\n");
      out.write("                            <div align=\"center\">\n");
      out.write("                                <input type=\"submit\" name=\"Submit\" value=\"Login\" />\n");
      out.write("                        </div></td>\n");
      out.write("                    </tr>\n");
      out.write("                </table>\n");
      out.write("        </div></form>\n");
      out.write("        <p align=\"right\">&nbsp;</p>\n");
      out.write("        <p>&nbsp;</p>\n");
      out.write("        <p>&nbsp;</p>\n");
      out.write("        <p>&nbsp;</p>\n");
      out.write("        <p>&nbsp;</p>\n");
      out.write("        <p>&nbsp;</p>\n");
      out.write("    <p>&nbsp;</p>    </td>\n");
      out.write("    </tr>\n");
      out.write("</table>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
